accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from . import views
from .views import BlogCreateView, BlogUpdateView
from .views import BlogCreateView, ShowProfilePageView, CreateProfilePageView, BlogDeleteView


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('user_profile/<int:pk>/', ShowProfilePageView.as_view(), name='user_profile'),
    path('create_profile_page/', CreateProfilePageView.as_view(), name='create_user_profile'),
    path('post/<int:pk>/delete/', BlogDeleteView.as_view(), name='post_delete'),
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls', namespace='blog')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[str(self.id)])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank=True)
    profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile/")
    facebook = models.CharField(max_length=50, null=True, blank=True)
    twitter = models.CharField(max_length=50, null=True, blank=True)
    instagram = models.CharField(max_length=50, null=True, blank=True)


def __str__(self):
    return str(self.user)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from taggit.models import Tag

from .forms import EmailPostForm, CommentForm
from .models import Post, Profile


class CreateProfilePageView(CreateView):
    model = Profile

    template_name = 'templates/create_profile.html'
    fields = ['profile_pic', 'bio', 'facebook', 'twitter', 'instagram']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy('tasks')


class ShowProfilePageView(DetailView):
    model = Profile
    template_name = 'templates/user_profile.html'

    def get_context_data(self, *args, **kwargs):
        users = Profile.objects.all()
        context = super(ShowProfilePageView, self).get_context_data(**kwargs)
        page_user = get_object_or_404(Profile, id=self.kwargs['pk'])
        context['page_user'] = page_user
        return context


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html',
                  {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading " {}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


class BlogCreateView(CreateView):
    model = Post
    template_name = 'blog/post_new.html'
    fields = ['title', 'author', 'body']


class BlogDetailView(DetailView):
    model = Post
    template_name = 'detail.html'


class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_edit.html'
    fields = ['title', 'body']


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('home')

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<html>
<head>
 <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=SplineSans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body>
 <div id="content">
  {% block content %}
      {% endblock %}
    </div>
 <div id="sidebar">
  {% if user.is_authenticated %}
        <h2><p>Hi {{ user.username }}!</p></h2>
        <h3><a href="{% url 'blog:post_new' %}">+ New Blog Post</a></h3>
        <h4><a href="{% url 'logout' %}">Log out</a></h4>
      {% else %}
        <p>You are not logged in.</p>
        <a href="{% url 'login' %}">Log In</a>
        <a href="{% url 'signup' %}">Sign Up</a>
      {% endif %}
  <h2>My blog</h2>
  <p>This is my blog. I've written {% total_posts %} posts so far.</p>
  <h3>Latest posts</h3>
  {% show_latest_posts 3 %}
  <h3>Most commented posts</h3>
 {% get_most_commented_posts as most_commented_posts %}
 <ul>
  {% for post in most_commented_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
  {% endfor %}
 </ul>
 </div>
</body>
</html>>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
  
{% block title %}{{ post.title }}{% endblock %}  
  
{% block content %}  
  <h1>{{ post.title }}</h1>
  <p class="date">
    <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
    Published {{ post.publish }} by {{ post.author }}  
  </p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url 'blog:post_share' post.id %}">
     Share this post
    </a>
  </p>
{% if user.is_authenticated %}
<p><a href="{% url 'blog:post_delete' post.pk %}">Delete Blog Post</a></p>
{% endif %}
  {% if new_comment %}
  <h2>Your comment has been added.</h2>
{% else %}
  <h2>Add a new comment</h2>
  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
  </form>
{% endif %}
  {% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
  {{ comment.body|linebreaks }}
  </div>
  {% empty %}
  <p>There are no comments yet.</p>
  {% endfor %}
  {% with comments.count as total_comments %}
  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}
  <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
  </h2>
  {% endwith %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
  
{% block title %}My Blog{% endblock %}  
  
{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
  <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}  
    <h2>  
      <a href="{{ post.get_absolute_url }}">
       {{ post.title }}  
      </a>
    </h2>
    <p class="tags">
        Tags:
     {% for tag in post.tags.all %}
     <a href='{% url "blog:post_list_by_tag" tag.slug %}'>
       {{ tag.name }}
     </a>
     {% if not forloop.last %}, {% endif %}
     {% endfor %}
    </p>
    <p class="date">  
      Published {{ post.publish }} by {{ post.author }}  
    </p>  
    {{ post.body|markdown|truncatewords_html:30 }}
   {% include "pagination.html" with page=posts %}
  {% endfor %}  
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}  
  
{% block title %}Share a post{% endblock %}  
  
{% block content %}  
  {% if sent %}  
    <h1>E-mail successfully sent</h1>  
    <p>  
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.  
    </p>  
  {% else %}  
    <h1>Share "{{ post.title }}" by e-mail</h1>  
    <form action="." method="post">  
      {{ form.as_p }}  
      {% csrf_token %}  
      <input type="submit" value="Send e-mail">  
    </form>  
  {% endif %}  
{% endblock %}

blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}
 
{% block content %}
    <h1>Delete post</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ post.title }}"?</p>
      <input type="submit" value="Confirm" />
    </form>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}
 
{% block content %}
    <h1>Edit post</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock content %}

blog/templates/blog/post_new.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>New post</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save" />
    </form>
{% endblock content %}

blog/templates/create_profile.html
{% extends "blog/base.html" %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="header-bar">
            <a href="{% url 'blog:tasks' %}">&#8592; Back</a>
        </div>
    &lt;div class="card-body"&gt;
        &lt;form method="POST" action="" enctype="multipart/form-data"&gt;
            {% csrf_token %}
            {{form.as_p}}
            &lt;input class="button" type="submit" value="Submit"&gt;
        &lt;/form&gt;
    &lt;/div&gt;
{% else %}
    &lt;a href="{% url 'login' %}"&gt;Login&lt;/a&gt;
{% endif %}

{% endblock content %}

blog/templates/pagination.html
<div class="pagination">
 <span class="step-links">
  {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
  {% endif %}
    <span class="current">
  Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
  {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
  {% endif %}
  </span>
</div>

blog/templates/signup.html
{% extends "blog/base.html" %}
 
{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock content %}

blog/templates/user_profile.html
{% extends "blog/base.html" %}

{% block content %}

    <div class="header-bar">
        <h1>Profile</h1>

        <a href="{% url 'blog:tasks' %}">&#8592; Back</a>

    </div>

    <div class="card-body">
    {% if user.profile.profile_pic %}
      <img src="{{ profile.profile_pic.url }}" height=100 width=100><br><br>
    {% else %}
      <img src="{% static 'base\images\profile\user.png' %}" height=100 width=100><br><br>
    {% endif %}
      <p><strong>Username:</strong> {{ page_user }}</p><br><br>
      <p><strong>Bio:</strong> {{ profile.bio }}</p><br><br>
      {% if profile.twitter %}
      <p><strong>Twitter:</strong> {{ profile.twitter }}</p><br><br>
      {% endif %}
      {% if profile.instagram %}
      <p><strong>Instagram:</strong> {{ profile.instagram }}</p><br><br>
      {% endif %}
      {% if profile.facebook %}
      <p><strong>Facebook:</strong> {{ profile.facebook }}</p><br><br>
      {% endif %}

      {% if user.id == profile.user.id %}
      <a href="{% url 'blog:edit_user_profile' profile.id %}"><button class="button">Edit</button></a>
      {% endif %}



    </div>

{% endblock content %}